# Generated by Django 3.0.5 on 2020-04-17 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceMotorcycle',
            fields=[
                ('date', models.DateField(null=True)),
                ('page', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bmodel', models.CharField(max_length=8)),
                ('decidedrate', models.IntegerField(null=True)),
                ('advance', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=10)),
                ('votes', models.PositiveIntegerField()),
                ('qty', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='CreditorApp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(blank=True, max_length=10)),
                ('cell', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date', models.DateField(null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('father', models.CharField(max_length=20, null=True)),
                ('cell', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('address', models.TextField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstallmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advancemotorcycle', to='CreditorApp.AdvanceMotorcycle')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('distance', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreditorApp.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('advance', models.CharField(max_length=10)),
                ('page', models.IntegerField(primary_key=True, serialize=False)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreditorApp.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreditorApp.Framework')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='CreditorApp.Genre'),
        ),
        migrations.AddField(
            model_name='advancemotorcycle',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermodel', to=settings.AUTH_USER_MODEL),
        ),
    ]
