# Generated by Django 3.0.5 on 2020-04-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreditorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageC', to='CreditorApp.Framework'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cellF', to='CreditorApp.Language'),
        ),
    ]
