# Generated by Django 3.0.5 on 2020-04-18 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreditorApp', '0004_auto_20200417_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancemotorcycle',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='installmentmodel',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inst', to='CreditorApp.AdvanceMotorcycle'),
        ),
    ]
