# Generated by Django 3.0.5 on 2020-04-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditorApp', '0005_auto_20200418_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='framework',
            name='bmodel',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='framework',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='framework',
            name='decidedrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='address',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='father',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
