# Generated by Django 3.0.5 on 2020-04-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditorApp', '0006_auto_20200418_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentmodel',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='installmentmodel',
            name='fine',
            field=models.IntegerField(null=True),
        ),
    ]
