# Generated by Django 3.0.5 on 2020-04-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditorApp', '0007_auto_20200422_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('OWNER', 1), ('MEMBER', 2), ('ADMIN', 3)], null=True),
        ),
    ]
