# Generated by Django 3.0.5 on 2020-04-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditorApp', '0009_auto_20200428_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staf',
            field=models.BooleanField(default=False),
        ),
    ]
