# Generated by Django 3.0.5 on 2020-04-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreditorApp', '0010_user_is_staf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staf',
            new_name='is_staff',
        ),
    ]
