# Generated by Django 3.0.5 on 2020-04-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreditorApp', '0011_auto_20200428_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
