# Generated by Django 3.0.5 on 2020-04-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreditorApp', '0017_auto_20200429_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
