# Generated by Django 3.0.5 on 2020-04-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreditorApp', '0018_auto_20200429_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_drive', 'Can drive'), ('can_vote', 'Can vote in elections'), ('can_drink', 'Can drink alcohol'))},
        ),
    ]
