# Generated by Django 3.0.5 on 2020-04-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditorApp', '0019_auto_20200429_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancemotorcycle',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='advancemotorcycle',
            name='month',
            field=models.IntegerField(null=True),
        ),
    ]
